### ISSUE TITLE
Cake 4.3.x issue: Subject must be an instance of Authentication\AuthenticationServiceInterface...

### ISSUE THREAD

**Issue by jicho** [k2rn/cakeauthissue#1]
Hi,

When I use the setup in your AuthenticationProvider setup from your project I'm getting the following error in CakePHP 4._3_:
```
Subject must be an instance of Authentication\AuthenticationServiceInterface or Authentication\AuthenticationServiceProviderInterface, App\Application given.
InvalidArgumentException
```

Do you have any idea how to solve that?
I'm liking the implementation, but it doesn't seem to work anymore...

Thanks!

**Comment by jicho** [comment]
Hmmm... just tried again... I think I did something wrong with the implementation/copy-past...

I have no idea what, but... it works now.

Thanks for reading ;)

**Comment by k2rn** [comment]
@jicho 
This code is not a working sample, just for show issue.
https://github.com/cakephp/authentication/issues/445

As you can see the issue above,
I don't recommend you strongly to use this example, they wouldn't expect code this way.

**Comment by jicho** [comment]
Thanks for the follow up!

I'm only used the example to get the AuthenticationMiddleware working in combination with the routes. Works great to split code up in seperate parts :)

For what I see that isn't  a problem.

I'm still using the RequestPolicy to manage the access rights.
